name: Scheduled update

on:
  schedule:
    - cron:  '0 * * * *'

jobs:
  update-currency-codes:
    name: Update currency code

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Execute updater
        run: bin/update-currency-codes

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          committer: The Respect Panda <therespectpanda@gmail.com>
          author: The Respect Panda <therespectpanda@gmail.com>
          title: Update list of commit messages
          branch: 2.0
